@local = https://localhost:7223
@curEnv = {{local}}

GET {{curEnv}}/api/v1/WeatherForecast

###

POST {{curEnv}}/api/v1/Tokens
Content-Type:application/json

{
    "Username": "Homer",
    "Password": "742EvergreenTerrace"
}

###

GET {{curEnv}}/api/v1/WeatherForecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSG9tZXIiLCJ1bmlxdWVfbmFtZSI6IkhvbWVyIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI1OCIsImF1ZCI6IldlYkFwaVRlbXBsYXRlIiwibmJmIjoiMTY4MDg4MDUzMCIsImV4cCI6IjE2ODA4ODQxMzAifQ.gSTSVO1JRq-HgR9K8lgoq21jb0ANjFgAuS5X5XGJGgE

###